# This workflow creates a draft release in github in response to 
# a v* tag push. It builds the python package and uploads the 
# distribution files to the release as assets for later manual publishing.
# Version tags like v1.0.0-beta.1, v2.1.0-rc.2, etc. are marked as pre-releases.

name: build release

on:
  push:
    tags:
    - 'v*' # Triggers on tags like v1.0.0, v2.1.3, etc., as well as v*.*.*-beta.*, v*.*.*-rc.*, etc.

permissions:
  contents: write  # To create a release

jobs:
  run-tests:
    # This is the same as the unit tests workflow, but could be extended with additional checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox -e py

  build-release:
    name: Build python package
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build the package
      run: python -m build
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }} # The tag that triggered the workflow
        name: ${{ github.ref_name }} # Name of the release
        prerelease: ${{ contains(github.ref, '-') }} # Marks the release as a pre-release if the tag contains a hyphen
        draft: true # Creates a draft release to allow for review before publishing
        files: 'dist/*'
        body: |
          Changes since last release:
          - TODO: Add changelog here.