# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# It also creates a new release in response to a version tag push

name: Build and run tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: lint
      run: tox -e lint
    - name: unit tests
      run: tox -e py

  build-release:
    name: Build python package on tag push
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    
    - name: Install dependencies
      run: python -m pip install --upgrade build tox twine
    
    - name: Build the package
      run: python -m build

    - name: Verify the package
      run: python -m twine check dist/*
    
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

    - name: Create Release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{ contains(github.ref, '-') }} # Marks the release as a pre-release if the tag contains a hyphen
        draft: true # Creates a draft release to allow for review before publishing
        files: 'dist/*'
        generate_release_notes: true
