# This workflow builds the python dist and uploads to pypi in response to a release being published
# For more information see: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: publish release to pypi

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-to-pypi:
    name: Publish python distribution to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install twine
      run: |
        python -m pip install --upgrade pip
        pip install twine

    - name: Download release assets
      uses: robinraju/release-downloader@v1.9
      with:
        tag: ${{ github.event.release.tag_name }}
        fileName: '*.whl'
        tarBall: true
        out-file-path: 'dist/'

    - name: Verify release assets
      run: |
        python -m twine check dist/*

    - name: Publish to TestPyPI (prerelease only)
      if: ${{ github.event.release.prerelease }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Publish to PyPI (release only)
      if: ${{ !github.event.release.prerelease }}
      uses: pypa/gh-action-pypi-publish@release/v1


