# This workflow builds the python dist and uploads to test pypi in response to a release being created
# For more information see: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: publish test release

on:
  release:
    types: [ published, edited ]

jobs:
  build:
    name: Build dist package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install build
      run: pip install build
    - name: Build binary wheel and a source tarball
      run: python -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/


  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest
    needs:
    - build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/puzpy

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download dist package
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/